name: Execução de testes regressivos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 8,16 * * 1,2,3,4,5'  # Executa 8h e 16h dos dias uteis (detalhes linha 42)

jobs:
  build_project:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Realiza o checkout do código

      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Instalar dependências
        run: |
          # Dependendo do seu projeto, execute o comando adequado para instalar as dependências
          # Exemplo para um projeto Maven
          mvn install

      - name: Executar testes
        run: |
          # Exemplo para rodar testes JUnit com Maven
          mvn test

      - name: Upload resultados dos testes
        if: always()  # Executar mesmo se os testes falharem
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target\test-classes  # Caminho onde os resultados dos testes ficarão

# Cron Expression (Lembrete):
  # *  *  *  *  *
  # |  |  |  |  |
  # |  |  |  |  +---- Dia da semana (0 - 7) (Domingo = 0 ou 7)
  # |  |  |  +------ Mês (1 - 12)
  # |  |  +-------- Dia do mês (1 - 31)
  # |  +---------- Hora (0 - 23)
  # +------------ Minuto (0 - 59)